"""empty message

Revision ID: 48b8acfc5c1a
Revises: f634be2f7c36
Create Date: 2025-05-08 11:50:25.670081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b8acfc5c1a'
down_revision = 'f634be2f7c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('is_complete',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('is_complete',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
